### ISSUE TITLE
Traceback on parsing email without info which email caused it.

### ISSUE THREAD

**Issue by mwdg** [kdeldycke/mail-deduplicate#132]
I'm deduping a large maildir.

Command line:
`mdedup -n -S 0 -C 0 -a move-selected -e maildir -E ~/mail/Maildir/.GMAllMailNonDupe -s select-oldest  ~/mail/Maildir/`

Output ends with:
`Check mail differences are below the thresholds.
Select all mails sharing the oldest 1299180509 timestamp...
warning: Skip set: all 5 mails within were selected. The strategy criterion was not able to discard some.
◼ 7 mails sharing hash faad932b06e1bed2520658105bcae3d483acf05fd605db23f365adc6
Check mail differences are below the thresholds.
Traceback (most recent call last):
  File "/usr/local/bin/mdedup", line 8, in <module>
    sys.exit(mdedup())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mail_deduplicate/cli.py", line 385, in mdedup
    dedup.select_all()
  File "/usr/local/lib/python3.9/site-packages/mail_deduplicate/deduplicate.py", line 417, in select_all
    candidates = duplicates.select_candidates()
  File "/usr/local/lib/python3.9/site-packages/mail_deduplicate/deduplicate.py", line 277, in select_candidates
    selected = apply_strategy(self.conf.strategy, self)
  File "/usr/local/lib/python3.9/site-packages/mail_deduplicate/strategy.py", line 262, in apply_strategy
    return set(method(duplicates))
  File "/usr/local/lib/python3.9/site-packages/mail_deduplicate/strategy.py", line 49, in select_oldest
    f"Select all mails sharing the oldest {duplicates.oldest_timestamp} "
  File "/usr/local/lib/python3.9/site-packages/boltons/cacheutils.py", line 610, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.9/site-packages/mail_deduplicate/deduplicate.py", line 156, in oldest_timestamp
    return min(map(attrgetter("timestamp"), self.pool))
  File "/usr/local/lib/python3.9/site-packages/boltons/cacheutils.py", line 610, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.9/site-packages/mail_deduplicate/mail.py", line 118, in timestamp
    value = email.utils.mktime_tz(email.utils.parsedate_tz(value))
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/email/_parseaddr.py", line 185, in mktime_tz
    if data[9] is None:
TypeError: 'NoneType' object is not subscriptable`

It looks to me like there's a defective email, but how am I supposed to figure out which one?

**Comment by leggewie** [comment]
Hello and thank you for your report.  Do you not get error messages in Phase 1 like I do in #155?  What is the output of "mdedup --version"?

**Comment by mwdg** [comment]
I tried adding the -H switch to the same command line (hope that's valid):

```shell-session
mdedup -n -H -S 0 -C 0 -a move-selected -e maildir -E ~/mail/Maildir/.GMAllMailNonDupe -s select-oldest  ~/mail/Maildir/
```
It crashed with this:

```pytb
...
15 mails found.
76 mails found.
3 mails found.
0 mails found.
0 mails found.
Mail sources  [####################################]  1/1

● Phase #1 - Compute hashes and group duplicates
Use [date, from, to, subject, mime-version, content-type, content-disposition, user-agent, x-priority, message-id] headers to compute hashes.
Hashed mails  [####################################]  166405/166405          
Traceback (most recent call last):
  File "/usr/local/bin/mdedup", line 8, in <module>
    sys.exit(mdedup())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mail_deduplicate/cli.py", line 380, in mdedup
    click.echo(mail.pretty_headers)
AttributeError: 'MaildirDedupMail' object has no attribute 'pretty_headers'`
```
The output of `mdedup --version` is:

```
mdedup 6.0.2
{'username': '-', 'guid': 'd6c8125a96344232225e5b1af003146', 'hostname': '-', 'hostfqdn': '-', 'uname': {'system': 'Darwin', 'node': '-', 'release': '19.6.0', 'version': 'Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64', 'machine': 'x86_64', 'processor': 'i386'}, 'linux_dist_name': '', 'linux_dist_version': '', 'cpu_count': 4, 'fs_encoding': 'utf-8', 'ulimit_soft': 256, 'ulimit_hard': 9223372036854775807, 'cwd': '-', 'umask': '0o2', 'python': {'argv': '-', 'bin': '-', 'version': '3.9.1 (default, Jan 8 2021, 17:17:17) [Clang 12.0.0 (clang-1200.0.32.28)]', 'compiler': 'Clang 12.0.0 (clang-1200.0.32.28)', 'build_date': 'Jan  8 2021 17:17:17', 'version_info': [3, 9, 1, 'final', 0], 'features': {'openssl': 'OpenSSL 1.1.1i  8 Dec 2020', 'expat': 'expat_2.2.8', 'sqlite': '3.34.0', 'tkinter': '8.6', 'zlib': '1.2.11', 'unicode_wide': True, 'readline': True, '64bit': True, 'ipv6': True, 'threading': True, 'urandom': True}}, 'time_utc': '2021-01-25 02:44:22.370920', 'time_utc_offset': -8.0, '_eco_version': '1.0.1'}
```

**Comment by mwdg** [comment]
For the original problem, I'm not getting any errors or warnings in Phase 1:

`● Phase #1 - Compute hashes and group duplicates
Use [date, from, to, subject, mime-version, content-type, content-disposition, user-agent, x-priority, message-id] headers to compute hashes.
Hashed mails  [####################################]  166405/166405`

**Comment by leggewie** [comment]
Hello and sorry for the delayed response.  Would you mind to update your installation to the latest release (for example via `pip3 install -U mail-deduplicate`) and let us know if you can still reproduce the issue there?

**Comment by rrthomas** [comment]
Installation of the latest version didn't work for me:

```
$ pip3 install -U mail-deduplicate
Collecting mail-deduplicate
  Downloading mail_deduplicate-6.2.0-py3-none-any.whl (38 kB)
Requirement already satisfied, skipping upgrade: arrow<1.2,>=0.17 in ./.local/lib/python3.8/site-packages (from mail-deduplicate) (0.17.0)
Requirement already satisfied, skipping upgrade: click-log<0.4.0,>=0.3.2 in ./.local/lib/python3.8/site-packages (from mail-deduplicate) (0.3.2)
Collecting tomlkit<0.8.0,>=0.7.0
  Downloading tomlkit-0.7.2-py2.py3-none-any.whl (32 kB)
Requirement already satisfied, skipping upgrade: click-help-colors<0.10,>=0.8 in ./.local/lib/python3.8/site-packages (from mail-deduplicate) (0.8.1)
Requirement already satisfied, skipping upgrade: tabulate<0.9.0,>=0.8.7 in ./.local/lib/python3.8/site-packages (from mail-deduplicate) (0.8.7)
Collecting click<9.0.0,>=8.0.0
  Downloading click-8.0.3-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 3.1 MB/s 
Requirement already satisfied, skipping upgrade: boltons<22.0.0,>=20.2.1 in ./.local/lib/python3.8/site-packages (from mail-deduplicate) (20.2.1)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.0 in ./.local/lib/python3.8/site-packages (from arrow<1.2,>=0.17->mail-deduplicate) (2.8.1)
Requirement already satisfied, skipping upgrade: six>=1.5 in ./.local/lib/python3.8/site-packages (from python-dateutil>=2.7.0->arrow<1.2,>=0.17->mail-deduplicate) (1.15.0)
ERROR: click-help-colors 0.8.1 has requirement click<8,>=7.0, but you'll have click 8.0.3 which is incompatible.
```

**Comment by feluxe** [comment]
```shell-session
  > mdedup --input-format maildir --hash-only --export copy-selected --dry-run -v mailbox/INBOX
```
```pytb
● Step #1 - Load mails
Mail sources  [------------------------------------]  0/1info:
Opening /tmp/mailbox/INBOX ...
warning: Forcing maildir format.
info: 9119 mails found.
Mail sources  [####################################]  1/1

● Step #2 - Compute hashes and group duplicates
info: Use [date, from, to, subject, mime-version, content-type, content-disposition, user-agent, x-priority, message-id] headers to compute hashes.
Hashed mails  [####################################]  9119/9119
Traceback (most recent call last):
  File "/home/peter/.local/bin/mdedup", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/peter/.local/pipx/venvs/mail-deduplicate/lib/python3.13/site-packages/mail_deduplicate/__main__.py", line 45, in main
    mdedup(prog_name=mdedup.name)
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/.local/pipx/venvs/mail-deduplicate/lib/python3.13/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/peter/.local/pipx/venvs/mail-deduplicate/lib/python3.13/site-packages/click_extra/commands.py", line 360, in main
    return super().main(*args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/peter/.local/pipx/venvs/mail-deduplicate/lib/python3.13/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/peter/.local/pipx/venvs/mail-deduplicate/lib/python3.13/site-packages/click_extra/commands.py", line 390, in invoke
    return super().invoke(ctx)
           ~~~~~~~~~~~~~~^^^^^
  File "/home/felix/.local/pipx/venvs/mail-deduplicate/lib/python3.13/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felix/.local/pipx/venvs/mail-deduplicate/lib/python3.13/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/felix/.local/pipx/venvs/mail-deduplicate/lib/python3.13/site-packages/cloup/_context.py", line 47, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/felix/.local/pipx/venvs/mail-deduplicate/lib/python3.13/site-packages/mail_deduplicate/cli.py", line 415, in mdedup
    echo(mail.pretty_headers)
         ^^^^^^^^^^^^^^^^^^^
AttributeError: 'MaildirDedupMail' object has no attribute 'pretty_headers'
```

Same. I don't get any info for which email it crashed.

**Comment by kdeldycke** [comment]
I just fixed this bug upstream: now duplicate sets containing mails without a parseable `Date` header are skipped.

This will be available in the upcoming release of mail-deduplicate 9.1.0.
