### ISSUE TITLE
latest version crashes with "Not enough data from canonical headers to compute reliable hash"

### ISSUE THREAD

**Issue by jult** [kdeldycke/mail-deduplicate#27]
``` python
WARNING: ignoring problematic /var/qmail/mailnames/xx.nl/xx/Maildir/new/1436223346.M611808P3746.xx.xx.eu,S=321,W=328: Not enough data from canonical headers to compute reliable hash!
Headers:
--------- 8< --------- 8< --------- 8< --------- 8< --------- 8< ---------
Message-ID: <8[10
--------- 8< --------- 8< --------- 8< --------- 8< --------- 8< ---------

..Traceback (most recent call last):
  File "./maildir-deduplicate.py", line 616, in <module>
    main()
  File "./maildir-deduplicate.py", line 560, in main
    duplicates_run(opts, maildir_paths)
  File "./maildir-deduplicate.py", line 578, in duplicates_run
    mail_count += collate_folder_by_hash(mails_by_hash, maildir, opts.message_id)
  File "./maildir-deduplicate.py", line 331, in collate_folder_by_hash
    mail_hash, header_text = compute_hash_key(mail_file, message, use_message_id)
  File "./maildir-deduplicate.py", line 315, in compute_hash_key
    canonical_headers_text = get_canonical_headers(mail_file, message)
  File "./maildir-deduplicate.py", line 226, in get_canonical_headers
    canonical_value = get_canonical_header_value(header, value)
  File "./maildir-deduplicate.py", line 285, in get_canonical_header_value
    utc_timestamp = email.utils.mktime_tz(parsed)
  File "/usr/lib64/python2.6/email/_parseaddr.py", line 142, in mktime_tz
    if data[9] is None:
TypeError: 'NoneType' object is unsubscriptable
```

The error is not very descriptive to me, what does it mean?

**Comment by kdeldycke** [comment]
Probably related to #24.

**Comment by aspiers** [comment]
Doesn't look like it's related to #24 - the output seems to clearly show that the script was fed an invalid email.  @jult You should check that file and verify whether it's a valid email.

**Comment by jult** [comment]
It was a valid email, 100% certain. I went with another tool for this in the end, which worked nicely.

**Comment by serussell** [comment]
@jult Surprise!  Blast from the past!  Which tool?

**Comment by jult** [comment]
@serussell Wow, I honestly don't remember. And I no longer have access to the servers I did this on, which is unfortunate, because I could check in .bash_history and probably left the tool somewhere under /root

**Comment by serussell** [comment]
@jult ok, thanks.  The search for a working tool continues...

**Comment by kdeldycke** [comment]
Let's close this issue for its age, especially in regards to the big rewrite this project has seen since then.
